### ISSUE TITLE
Utilizar PSR's 1, 2 e 4.

### ISSUE THREAD

**Issue by verzola** [dacolera/aeskaeno#4]
As PSR's foram criadas pela FIG (Framework Interop Group), que é uma organização criada com o objetivo de padronizar as diferenças entre os frameworks para que os pacotes sejam mais compativeis entre eles.

A PSR-0 e PSR-4 determina um padrão de autoload de classes, a PSR-1 e PSR-2 determinam padrões de estilo de código. Já a PSR-3 determina um padrão de Logger. A PSR-0 foi depreciada em favor da 4.

Usar as PSR's fazem com que a leitura do código fique padronizada e o carregamento das classes seja simples.

Leia mais em: http://www.php-fig.org/

**Comment by verzola** [comment]
Falta deixar os namespaces em maiúsculo.

**Comment by dacolera** [comment]
Ja coloquei todos em maiusculo
