### ISSUE TITLE
Utilizar um Container de Injeção de Dependência

### ISSUE THREAD

**Issue by verzola** [dacolera/aeskaeno#5]
Todas as classes do sistema extendem a classe principal, que é "Askaeno".
Essa arquitetura acopla muito os componentes do sistema.

Utilizar um Container de Injeção de Dependência é uma das formas de Inversão de Dependência (5º conceito do SOLID) e permite criar classes que não tem conhecimento da implementação concreta de outras classes, facilitando a extensão do framwork.

Leia mais em:
http://www.devmedia.com.br/padrao-de-injecao-de-dependencia/18506

Segue 2 links de Containers de Injeção de Dependência:
PHP-DI - http://php-di.org/
Pimple - http://pimple.sensiolabs.org/

**Comment by dacolera** [comment]
Adicionei de forma rustica ainda o zend\servicemanager, porem o desacoplamento ja comecou.
