### ISSUE TITLE
Reduzir acoplamento

### ISSUE THREAD

**Issue by verzola** [dacolera/aeskaeno#9]
Os componentes do framework estão muito acoplados entre si.
O Controller depende do Core, o Model extende o Core e o Core é muito genérico e faz muitas coisas.

**Comment by dacolera** [comment]
Vou trabalhar nisso. Por enquanto usarei composicao para levar os metodos do core para as abstracts Model e controller. Isso vai reduzir o acoplamento a espera de uma solucao mais elegante. Valeu.
